### ISSUE TITLE
能否写个ios或调用示例呢

### ISSUE THREAD

**Issue by beiguancyc** [Easy-Martin/JSBridge#1]
第一次学习原生与web的交互，请问能否写个ios或android调用示例呢？非常感谢

**Comment by Easy-Martin** [comment]
跟ios和安卓没有关系 调用都是一样的  demo里面有呀

**Comment by Easy-Martin** [comment]
readme下面有原生实现的方案，可以给你们原生开发的同学看看是不是用的一样的

**Comment by beiguancyc** [comment]
> readme下面有原生实现的方案，可以给你们原生开发的同学看看是不是用的一样的

非常感谢
